<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.5.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.*" />
    <PackageReference Include="Moq" Version="4.20.*" />
    <PackageReference Include="FluentAssertions" Version="6.12.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SkillDuel.Api\SkillDuel.Api.csproj" />
    <ProjectReference Include="..\..\src\SkillDuel.Application\SkillDuel.Application.csproj" />
    <ProjectReference Include="..\..\src\SkillDuel.Domain\SkillDuel.Domain.csproj" />
    <ProjectReference Include="..\..\src\SkillDuel.Infrastructure\SkillDuel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
